apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: Devops
  region: ap-south-1

vpc:
  id: vpc-0fa9e4d986269b8b3
  cidr: "192.168.0.0/16"
  subnets:
    public:
      ap-south-1a:
        id: subnet-03197965f36167fb6
      ap-south-1b:
        id: subnet-0d2ce523b4cbded7e

nodeGroups:
  - name: jenkins-node-group
    labels: { role: jenkins }
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true
  - name: nexus-node-group
    labels: { role: nexus }
    instanceType: t2.medium
    desiredCapacity: 2