apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: Devops-Tools
  region: ap-south-1

vpc:
  id: vpc-03e19fa33d6173b69
  cidr: "192.168.0.0/16"
  subnets:
    public:
      ap-south-1a:
        id: subnet-0dc5ebba7e18e1b74
      ap-south-1b:
        id: subnet-033444637443f874d
    private:
      ap-south-1a:
        id: subnet-0d647278b03bfe3c4
      ap-south-1b:
        id: subnet-0a42285b27863b65b

nodeGroups:
  - name: Devops-Tools-Workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: Devops-Tools-Workers-2
    instanceType: t2.medium
    desiredCapacity: 2
    privateNetworking: true