apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: Devops-Tools-Cluster
  region: ap-south-1

vpc:
  id: vpc-0070a9f472896af90
  cidr: "10.0.0.0/25"
  subnets:
    public:
      ap-south-1a:
        id: subnet-006e38aee027286bf
      ap-south-1b:
        id: subnet-068cbad9062362287
    private:
      ap-south-1a:
        id: subnet-0047c0d79c18c277b
      ap-south-1b:
        id: subnet-0d328be35d9539307

nodeGroups:
  - name: Devops-Tools-Workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: Devops-Tools-Workers-2
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true