apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-tools
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      tool-name: jenkins
      role: jenkins 
  template:
    metadata:
      labels:
        tool-name: jenkins
    spec:
      nodeSelector:
        tool: jenkins
      containers:
        - name: jenkins
          image: jenkins:2.60.3
          ports:
            - containerPort: 8080