apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-tools
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      nodeSelector:
        role: jenkins-public
      containers:
        - name: jenkins
          image: jenkins:2.60.3
          ports:
            - containerPort: 8080