apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-jenkins
  namespace: devops
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: jenkins
        image: 373341467727.dkr.ecr.ap-south-1.amazonaws.com/devopscontainers:jenkins
        ports:
        - name: http
          containerPort: 80
        - name: jenkinsport
          containerPort: 8080
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux