apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  namespace: devops
  labels:
    role: jenkins
spec:
    containers:
      - name: jenkins
        image: jenkins:2.60.3
        ports:
          - containerPort: 8080
    nodeSelector:
      role: jenkins