apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    role: jenkins
spec:
  containers:
      containers:
        - name: jenkins
          image: jenkins:2.60.3
          ports:
            - containerPort: 8080
      nodeSelector:
        role: jenkins