apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: nexus
  ports:
    - nodePort: 31420
      port: 8081
      targetPort: 8081