apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-tools-nexus
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      nodeSelector:
        role: nexus-public
      containers:
        - name: nexus3
          image: sonatype/nexus3:latest
          ports:
            - containerPort: 8081

          