apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-tools
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      tool-name: nexus3 
  template:
    metadata:
      labels:
        tool-name: nexus3
    spec:
      containers:
        - name: nexus3
          image: sonatype/nexus3:latest
          ports:
            - containerPort: 8081
          