apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  selector:
    matchLabels:
      tool-name: jenkins
  replicas: 1
  template:
    metadata:
      labels:
        tool-name: jenkins
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: tool-name
                operator: In
                values:
                - jenkins
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: jenkins
        image: jenkins:2.60.3