apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: devops
spec:
  type: NodePort
  selector:
    tool-name: jenkins
  ports:
    - nodePort: 31429
      port: 8080
      targetPort: 8080